 CREATE TABLE `cp_pricemaking_mapping` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` varchar(32) COLLATE utf8_bin NOT NULL,
  `MAPPING_BEFORE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `MAPPING_AFTER` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `IS_VALID` char(1) COLLATE utf8_bin DEFAULT NULL,
  `COMMENT` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;