INSERT INTO `amc_dr_bill_subject_map` (`TENANT_ID`, `DR_SUBJECT`, `BILL_SUBJECT`) VALUES ('ECITIC', 'ZBJZ01', '300013');
INSERT INTO `amc_dr_bill_subject_map` (`TENANT_ID`, `DR_SUBJECT`, `BILL_SUBJECT`) VALUES ('ECITIC', 'CMSTOP01', '300014');
INSERT INTO `amc_deduct_rule` (`TENANT_ID`, `FUND_SUBJECT`, `FEE_SUBJECT`) VALUES ('ECITIC', '100001', '300013');
INSERT INTO `amc_deduct_rule` (`TENANT_ID`, `FUND_SUBJECT`, `FEE_SUBJECT`) VALUES ('ECITIC', '100001', '300014');
commit;