
/*注意：请更新amc_charge_yyyydd及每月月表*/


ALTER TABLE `amc_charge_yyyydd` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201602` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201603` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201604` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201605` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201606` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201607` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201608` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201609` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201610` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201611` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201612` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201701` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201702` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201703` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;


ALTER TABLE `amc_charge_201704` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201705` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201706` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201707` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201708` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201709` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201710` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201711` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;

ALTER TABLE `amc_charge_201712` 
ADD COLUMN `DR_TOTAL_AMOUNT` DECIMAL(15,3) NULL AFTER `TENANT_ID`;