ALTER TABLE `dev_baas_bmc1`.`rtm_output_detail_yyyymm` 
CHANGE COLUMN `SN` `SN` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `bsn` `bsn` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '' ;
