insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '340', 'ECITIC', 'ORDER_FAIL_CODE', '000001', 'json校验异常', null, 'json校验异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '341', 'ECITIC', 'ORDER_FAIL_CODE', '000002', '格式转换异常', null, '格式转换异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '342', 'ECITIC', 'ORDER_FAIL_CODE', '000003', '机构ID查询失败', null, '机构ID查询失败', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '343', 'ECITIC', 'ORDER_FAIL_CODE', '000004', '价格查询异常', null, '价格查询异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '344', 'ECITIC', 'ORDER_FAIL_CODE', '000005', '分摊信息查询异常', null, '分摊信息查询异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '345', 'ECITIC', 'ORDER_FAIL_CODE', '000006', '资费表沉淀异常', null, '资费表沉淀异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '346', 'ECITIC', 'ORDER_FAIL_CODE', '000007', '重复订购', null, '重复订购', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '347', 'ECITIC', 'ORDER_FAIL_CODE', '000008', '订购服务调用异常', null, '订购服务调用异常', null);
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '348', 'ECITIC', 'ORDER_FAIL_CODE', '000009', '订购失败', null, '订购失败', null);
--注意:订购接口地址随环境改变
insert into `dev_baas_bmc1`.`bmc_basedata_code` ( `id`, `tenant_id`, `param_type`, `param_code`, `param_name`, `default_value`, `comments`, `parent_code`) values ( '96', 'ECITIC', 'ORDER_URL', 'http://order.citicdao-te.com/baas-batch-order/citic/instanceOrder', '中信订购url', null, '中信订购rest接口', null);