insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2025,168,'bl_subs_comm',1,'SUBS_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2026,168,'bl_subs_comm',2,'PRODUCT_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2027,168,'bl_subs_comm',3,'SUBS_PRODUCT_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2028,168,'bl_subs_comm',4,'RES_BONUS_FLAG',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2029,168,'bl_subs_comm',5,'ACTIVE_TIME',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2030,168,'bl_subs_comm',6,'INACTIVE_TIME',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2031,168,'bl_subs_comm',7,'TENANT_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2032,168,'bl_subs_comm',8,'CUST_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2033,168,'bl_subs_comm',9,'PRODUCT_TYPE',0,null,null,0,0,null,'BYD');

insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2086,182,'cp_package_info',1,'PACKAGE_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2087,182,'cp_package_info',2,'DETAIL_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2088,182,'cp_package_info',3,'AMOUNT',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2089,182,'cp_package_info',4,'PRICE_VALUE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2090,182,'cp_package_info',5,'TOTAL_PRICE_VALUE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2091,182,'cp_package_info',6,'UNIT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2092,182,'cp_package_info',7,'UNIT_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2093,182,'cp_package_info',8,'FACTOR_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2094,182,'cp_package_info',9,'EXCEED_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2095,182,'cp_package_info',10,'UNITPRICE_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2096,182,'cp_package_info',11,'EXT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2097,182,'cp_package_info',12,'SUBJECT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2098,182,'cp_package_info',13,'SERVICE_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2099,182,'cp_package_info',14,'IS_TOTAL_PRICE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2100,182,'cp_package_info',15,'CYCLE_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2101,182,'cp_package_info',16,'CYCLE_INTERVAL',0,null,null,0,0,null,'BYD');

insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2102,183,'cp_package_info',1,'PACKAGE_ID',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2103,183,'cp_package_info',2,'DETAIL_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2104,183,'cp_package_info',3,'AMOUNT',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2105,183,'cp_package_info',4,'PRICE_VALUE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2106,183,'cp_package_info',5,'TOTAL_PRICE_VALUE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2107,183,'cp_package_info',6,'UNIT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2108,183,'cp_package_info',7,'UNIT_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2109,183,'cp_package_info',8,'FACTOR_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2110,183,'cp_package_info',9,'EXCEED_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2111,183,'cp_package_info',10,'UNITPRICE_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2112,183,'cp_package_info',11,'EXT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2113,183,'cp_package_info',12,'SUBJECT_CODE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2114,183,'cp_package_info',13,'SERVICE_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2115,183,'cp_package_info',14,'IS_TOTAL_PRICE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2116,183,'cp_package_info',15,'CYCLE_TYPE',0,null,null,0,0,null,'BYD');
insert into `ebilling_shm_table_record`(`ID`,`TABLE_ID`,`TABLE_NAME`,`FIELD_SEQ`,`FIELD_NAME`,`FIELD_TYPE`,`FIELD_FORMAT`,`FIELD_SIZE`,`IS_HASHKEY`,`IS_PRIMARY`,`SEARCH_TYPE`,`tenant_id`) values (2117,183,'cp_package_info',16,'CYCLE_INTERVAL',0,null,null,0,0,null,'BYD');






